name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Zig Compiler
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Check Formatting
        run: zig fmt --check build.zig src test_initfs

      - name: Install test tools
        run: |
          sudo apt-get update
          sudo apt-get install -y just cpio

      - name: Build test initrds
        run: just initrds

      - name: Run Debug Tests
        run: zig build test

      - name: Run Tsan Tests
        run: zig build test -Dtsan=true

      - name: Run Release Tests
        run: zig build test --release=fast

